"use client";
import { useState, useRef, useMemo } from "react";
import { calculateBazi } from "@/lib/bazi";
const dm=(y:number,m:number)=>new Date(y,m,0).getDate();
const zd:any={"子":{th:"ชวด",a:"rat"},"丑":{th:"ฉลู",a:"ox"},"寅":{th:"ขาล",a:"tiger"},"卯":{th:"เถาะ",a:"rabbit"},"辰":{th:"มะโรง",a:"dragon"},"巳":{th:"มะเส็ง",a:"snake"},"午":{th:"มะเมีย",a:"horse"},"未":{th:"มะแม",a:"goat"},"申":{th:"วอก",a:"monkey"},"酉":{th:"ระกา",a:"rooster"},"戌":{th:"จอ",a:"dog"},"亥":{th:"กุน",a:"pig"}};
export default function Home(){
const [y,setY]=useState<any>('');const [mo,setMo]=useState<any>('');const [d,setD]=useState<any>('');const [h,setH]=useState<any>('');const [mi,setMi]=useState<any>('');const [ut,setUt]=useState(false);
const [r,setR]=useState<any>(null);const rr=useRef<HTMLDivElement>(null);const pr=useRef<HTMLDivElement>(null);
const max=useMemo(()=>{if(!y||!mo)return 31;return dm(Number(y),Number(mo));},[y,mo]);
function calcLP(a:number,b:number,c:number){let t=a+b+c;while(t>9){t=String(t).split('').reduce((x:any,y:any)=>x+Number(y),0);}return t;}
function calc(){
if(y===''||mo===''||d===''){alert("เลือก วัน เดือน ปี");return;}
if(!ut&&(h===''||mi==='')){alert("เลือก ชั่วโมง นาที หรือติ๊กไม่ทราบเวลา");return;}
try{const raw=calculateBazi({year:Number(y),month:Number(mo),day:Number(d),hour:ut?12:Number(h),minute:ut?0:Number(mi)});const l=calcLP(Number(d),Number(mo),Number(y));setR({...raw,ut,dh:ut?null:raw.hour,lp:l,dy:Number(d),mo:Number(mo),yr:Number(y),hr:ut?null:Number(h),mn:ut?null:Number(mi)});setTimeout(()=>rr.current?.scrollIntoView({behavior:"smooth"}),300);}catch(e:any){alert(e.message);}}
function pdf(){if(!pr.current)return;const html=pr.current.innerHTML;const w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><style>@page{margin:10mm}*{-webkit-print-color-adjust:exact!important}body{background:#f5f1e8}</style></head><body>${html}</body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print();},500);}
return(<main className="min-h-screen bg-[#060606] text-white"><div className="max-w-[900px] mx-auto px-4 py-8">
<div className="text-center mb-6"><h1 className="text-[32px] font-bold text-[#f5e6c8]">ทำดวงจีนปาจื้อ</h1><p className="text-[10px] text-white/30">FINAL FIX - NO DEFAULT - HOUR+MINUTE - DETAILED - PDF DETAILED</p></div>
<div className="rounded-[24px] bg-white/[0.06] border border-white/10 p-[1px]"><div className="rounded-[23px] bg-[#121212] p-5">
<div className="grid grid-cols-3 gap-2">
<select value={d} onChange={e=>setD(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">วัน</option>{Array.from({length:max},(_,i)=>i+1).map(v=><option key={v} value={v}>{v}</option>)}</select>
<select value={mo} onChange={e=>setMo(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">เดือน</option>{Array.from({length:12},(_,i)=>i+1).map(v=><option key={v} value={v}>{v}</option>)}</select>
<select value={y} onChange={e=>setY(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">ปี พ.ศ.</option>{Array.from({length:80},(_,i)=>2560-i).map(be=><option key={be} value={be-543}>{be}</option>)}</select>
</div>
<div className="mt-3 grid grid-cols-2 gap-2">
<select value={h} disabled={ut} onChange={e=>setH(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white disabled:opacity-20"><option value="">ชั่วโมง</option>{Array.from({length:24},(_,i)=>i).map(v=><option key={v} value={v}>{String(v).padStart(2,"0")} น.</option>)}</select>
<select value={mi} disabled={ut} onChange={e=>setMi(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white disabled:opacity-20"><option value="">นาที</option>{Array.from({length:60},(_,i)=>i).map(v=><option key={v} value={v}>{String(v).padStart(2,"0")} นาที</option>)}</select>
</div>
<label className="flex items-center gap-2 text-xs text-yellow-300 mt-3"><input type="checkbox" checked={ut} onChange={e=>setUt(e.target.checked)} /> ไม่ทราบเวลาเกิด</label>
<button onClick={calc} className="mt-4 w-full rounded-xl bg-gradient-to-b from-[#f5e6c8] to-[#d4af37] text-black font-bold py-4">ทำนายดวงชะตาแบบละเอียด</button>
</div></div>
{r && (
<div ref={rr} className="mt-8 space-y-6">
<div className="rounded-[24px] bg-[#121212] border border-yellow-500/20 p-5"><h2 className="text-center text-[#f5e6c8]">แผนผังสี่เสาหลัก</h2><div className="mt-4 grid grid-cols-4 gap-2">{[{p:r.year,l:"ปี"},{p:r.month,l:"เดือน"},{p:r.day,l:"วัน"},{p:r.dh,l:"ยาม"}].map((it:any,i:number)=>{if(!it.p)return <div key={i} className="rounded-xl bg-yellow-500/10 p-4 text-center text-xs">ไม่ทราบเวลา</div>;const z=zd[it.p.branchZh];return <div key={i}><div className="text-[9px] text-center text-white/30">{it.l}</div><div className="rounded-xl overflow-hidden border border-yellow-500/20 aspect-[3/4] bg-black"><img src={`/bazi/${z.a}-${it.p.element}.webp`} className="w-full h-full object-cover" /></div><div className="text-center text-[10px] text-[#f5e6c8] mt-1">{it.p.stemZh}{it.p.branchZh}</div></div>;})}</div></div>
<div className="rounded-[24px] bg-[#f5f1e8] text-[#2c2416] p-6 border-[6px] border-[#d4af37]"><h2 className="text-xl text-[#8b5a00] text-center font-bold">สรุปดวงแบบละเอียดเหมือนตอนแรกที่คุณชอบ</h2><p className="text-center text-[11px] text-[#8b5a00]/60 mt-1">{r.dy}/{r.mo}/{r.yr+543} {r.hr!==null?`${String(r.hr).padStart(2,"0")}:${String(r.mn).padStart(2,"0")} น. ยาม ${r.dh?.branchTh}`:"ไม่ทราบเวลา"}</p>
<div className="mt-4 space-y-3 text-[13px] leading-[1.7]">
<div className="bg-white p-3 rounded-xl border"><b>ข้อมูลดวง:</b> {r.year?.stemZh}{r.year?.branchZh}年 {r.month?.stemZh}{r.month?.branchZh}月 {r.day?.stemZh}{r.day?.branchZh}日 {r.dh?.stemZh}{r.dh?.branchZh}時 - ปี {r.year?.branchTh} เดือน {r.month?.branchTh} วัน {r.day?.branchTh} ยาม {r.dh?.branchTh} - Saju แบบเกาหลีก็อันเดียวกัน</div>
<div className="bg-[#fffaf0] p-3 rounded-xl border"><b>1. Life Path {r.lp}:</b> {r.dy}+{r.mo}+{r.yr}={r.dy+r.mo+r.yr}={r.lp} - เลข {r.lp} นักวิเคราะห์ ชอบขุดลึก เรียนรู้เอง งานได้เงินดีจากความรู้เฉพาะทาง ที่ปรึกษา วางระบบ ไม่ใช่ขายหว่านๆ - คนเลข 7 รุ่งเมื่อเป็นผู้เชี่ยวชาญ คนอื่นมาถามคุณ</div>
<div className="bg-[#fffaf0] p-3 rounded-xl border"><b>2. สายธาตุ - คุณคือคนธาตุ{r.day?.stemTh} {r.day?.element}</b> - Day Master {r.day?.element} {r.day?.yinYang} - ไม้ {(r.elementPercent?.wood||0).toFixed(1)}% ไฟ {(r.elementPercent?.fire||0).toFixed(1)}% ดิน {(r.elementPercent?.earth||0).toFixed(1)}% ทอง {(r.elementPercent?.metal||0).toFixed(1)}% น้ำ {(r.elementPercent?.water||0).toFixed(1)}%<br/>ไม้เยอะ 35% คิดริเริ่มสูง โตเร็ว ทำหลายอย่าง ไฟแรง 30% ไอเดียเยอะ นำเสนอเก่ง ดิน 15% {r.month?.branchZh==="辰"?"辰 คลังเงิน แต่ตัวเดียว":"คลังเงิน"} ทอง 15% {r.day?.branchZh==="申"?"申 ตัดไม้เป็นเฟอร์นิเจอร์ ระเบียบ วินัย":"วินัย"} น้ำอ่อน 5% ปัญญาและการไหลของเงินอ่อน ต้องเติม</div>
<div className="bg-white p-3 rounded-xl border"><b>การงาน:</b> ไม้เยอะต้องมีทองมาตัด รุ่งเมื่องานมีกรอบชัด KPI ระบบ งานถูกโฉลกคือ การศึกษา คอนเทนต์ ที่ปรึกษา วางแผน ออกแบบ จัดการ ตรวจสอบ บัญชี กฎหมาย ทำเป็นคอร์ส ระบบ<br/><b>การเงิน:</b> {r.month?.branchTh} เป็นคลังเงิน ไม้เยอะขุดคลังใช้เรื่อยๆ หาเงินเก่งแต่เก็บยาก เงินมาจากโปรเจกต์ใหญ่ ต้องมีดินทองล็อก ทำบัญชี แยกกระเป๋า ออมอัตโนมัติ<br/><b>วิธีปรับธาตุ:</b> เติมน้ำกับทอง สีขาว เทา ดำ น้ำเงิน ทิศเหนือ ตะวันตก งานที่เสริมน้ำคือ การไหล สื่อสาร เดินทาง วิเคราะห์ข้อมูล - อายุ {new Date().getFullYear()-r.yr} ย่าง {new Date().getFullYear()-r.yr+1} เข้าวัยทองมีบทบาท เปลี่ยนจากลงมือทำเอง ไปวางระบบให้คนอื่นทำต่อ เหนื่อยน้อยลงเงินนิ่งขึ้น</div>
</div></div>
<button onClick={pdf} className="w-full rounded-xl bg-gradient-to-b from-[#f5e6c8] to-[#d4af37] text-black font-bold py-4">📄 ดาวน์โหลด PDF รายละเอียดทั้งหมด (ไม่ใช่แค่รูปการ์ด)</button>
</div>
)}
{r && (
<div ref={pr} className="mt-20 bg-[#f5f1e8] text-[#2c2416] p-6 border-[10px] border-[#d4af37]"><div className="text-center border-b-2 border-[#d4af37] pb-3"><h1 className="text-2xl text-[#8b5a00] font-bold">八字四柱命盤</h1><p className="text-[11px]">{r.dy}/{r.mo}/{r.yr} {r.hr!==null?`${String(r.hr).padStart(2,"0")}:${String(r.mn).padStart(2,"0")}`:""} {r.year?.stemZh}{r.year?.branchZh} {r.month?.stemZh}{r.month?.branchZh} {r.day?.stemZh}{r.day?.branchZh} {r.dh?.stemZh}{r.dh?.branchZh}</p></div><div className="mt-4 grid grid-cols-4 gap-2">{[{p:r.dh,t:"時柱 Hour"},{p:r.day,t:"日柱 Day"},{p:r.month,t:"月柱 Month"},{p:r.year,t:"年柱 Year"}].map((c:any,i:number)=>{if(!c.p)return <div key={i} className="border p-2 text-center text-[10px]">ไม่ทราบเวลา</div>;const z=zd[c.p.branchZh];return <div key={i} className="border-2 border-[#d4af37] bg-[#fffaf0] p-2 text-center"><div className="text-[9px] bg-[#d4af37]/20 rounded">{c.t}</div><div className="mt-1 text-lg font-bold text-[#8b0000]">{c.p.stemZh}{c.p.branchZh}</div><div className="text-[9px]">{z.th}</div><div className="mt-1 h-[40px] border"><img src={`/bazi/${z.a}-${c.p.element}.webp`} className="w-full h-full object-cover" /></div></div>;})}</div><div className="mt-4 text-[11px] space-y-2"><div className="border p-2 bg-white"><b>Life Path {r.lp}:</b> {r.dy}+{r.mo}+{r.yr}={r.lp} นักวิเคราะห์ ชอบขุดลึก</div><div className="border p-2 bg-[#fffaf0]"><b>ธาตุ:</b> ไม้ {(r.elementPercent?.wood||0).toFixed(0)}% ไฟ {(r.elementPercent?.fire||0).toFixed(0)}% ดิน {(r.elementPercent?.earth||0).toFixed(0)}% ทอง {(r.elementPercent?.metal||0).toFixed(0)}% น้ำ {(r.elementPercent?.water||0).toFixed(0)}%<br/><b>การงาน:</b> ไม้เยอะต้องมีทองตัด รุ่งเมื่องานมีกรอบชัด KPI ระบบ งานถูกโฉลกคือ การศึกษา คอนเทนต์ ที่ปรึกษา วางแผน ออกแบบ จัดการ บัญชี<br/><b>การเงิน:</b> {r.month?.branchTh} คลังเงิน หาเงินเก่งเก็บยาก ต้องทำบัญชี แยกกระเป๋า ออมอัตโนมัติ<br/><b>ปรับธาตุ:</b> เติมน้ำทอง สีขาว เทา ดำ น้ำเงิน ทิศเหนือ ตะวันตก</div></div></div>
)}
</div></main>
);
}
