"use client";
import { useState, useRef, useMemo } from "react";
import { calculateBazi } from "@/lib/bazi";
const dm=(y:number,m:number)=>new Date(y,m,0).getDate();
const zd:any={"子":{th:"ชวด",a:"rat"},"丑":{th:"ฉลู",a:"ox"},"寅":{th:"ขาล",a:"tiger"},"卯":{th:"เถาะ",a:"rabbit"},"辰":{th:"มะโรง",a:"dragon"},"巳":{th:"มะเส็ง",a:"snake"},"午":{th:"มะเมีย",a:"horse"},"未":{th:"มะแม",a:"goat"},"申":{th:"วอก",a:"monkey"},"酉":{th:"ระกา",a:"rooster"},"戌":{th:"จอ",a:"dog"},"亥":{th:"กุน",a:"pig"}};
function st(p:number){if(p>=35)return"โดดเด่นมาก";if(p>=25)return"มีพลังมาก";if(p>=15)return"สมดุลดี";if(p>=8)return"ค่อนข้างน้อย";return"อ่อน";}
const lpData:any={1:{t:"ผู้นำ",d:"กล้าคิดกล้าทำ ชอบเริ่มใหม่ ธุรกิจส่วนตัว",r:"คนเลข 1 จะรุ่งเมื่อกล้าเป็นคนเริ่ม"},2:{t:"นักประสาน",d:"ละเอียดอ่อน ประสานงาน ที่ปรึกษา",r:"คนเลข 2 จะรุ่งเมื่อเป็นคู่คิด"},3:{t:"นักสื่อสาร",d:"พูดเก่ง เขียนเก่ง ครีเอทีฟ",r:"คนเลข 3 จะรุ่งเมื่อได้พูด แสดง"},4:{t:"นักวางระบบ",d:"มีระเบียบ รอบคอบ มั่นคง",r:"คนเลข 4 จะรุ่งเมื่อมีระบบชัด"},5:{t:"นักเดินทาง",d:"ไม่ชอบจำเจ ชอบอิสระ เปลี่ยนแปลง",r:"คนเลข 5 จะรุ่งเมื่อได้เดินทาง เปลี่ยน"},6:{t:"นักดูแล",d:"ใจดี รับผิดชอบ รักครอบครัว",r:"คนเลข 6 จะรุ่งเมื่อได้ดูแลคนอื่น"},7:{t:"นักวิเคราะห์",d:"ชอบคิดลึก เรียนรู้เอง ความรู้เฉพาะทาง",r:"คนเลข 7 จะรุ่งเมื่อเป็นผู้เชี่ยวชาญ คนอื่นต้องมาถามคุณ"},8:{t:"นักบริหาร",d:"มีเป้าหมายเงินชัด ภาวะผู้นำ",r:"คนเลข 8 จะรุ่งเมื่อได้บริหาร"},9:{t:"ผู้ให้",d:"ใจกว้าง มองภาพใหญ่ ชอบช่วยสังคม",r:"คนเลข 9 จะรุ่งเมื่อได้ให้"}};
export default function Home(){
const [y,setY]=useState<any>('');const [mo,setMo]=useState<any>('');const [d,setD]=useState<any>('');const [h,setH]=useState<any>('');const [mi,setMi]=useState<any>('');const [ut,setUt]=useState(false);
const [r,setR]=useState<any>(null);const rr=useRef<HTMLDivElement>(null);
const max=useMemo(()=>{if(!y||!mo)return 31;return dm(Number(y),Number(mo));},[y,mo]);
function lp(a:number,b:number,c:number){let t=a+b+c;while(t>9){t=String(t).split('').reduce((x:any,y:any)=>x+Number(y),0);}return t;}
function calc(){if(y===''||mo===''||d===''){alert("เลือก วัน เดือน ปี");return;}if(!ut&&(h===''||mi==='')){alert("เลือก ชั่วโมง นาที หรือติ๊กไม่ทราบเวลา");return;}try{const raw=calculateBazi({year:Number(y),month:Number(mo),day:Number(d),hour:ut?12:Number(h),minute:ut?0:Number(mi)});const l=lp(Number(d),Number(mo),Number(y));setR({...raw,ut,dh:ut?null:raw.hour,lp:l,dy:Number(d),mo:Number(mo),yr:Number(y),hr:ut?null:Number(h),mn:ut?null:Number(mi)});setTimeout(()=>rr.current?.scrollIntoView({behavior:"smooth"}),300);}catch(e:any){alert(e.message);}}
return(<main className="min-h-screen bg-[#060606] text-white"><div className="max-w-[900px] mx-auto px-4 py-8">
<div className="text-center mb-6"><h1 className="text-[36px] font-bold text-[#f5e6c8]">ทำนายดวงจีนปาจื้อ</h1></div>
<div className="rounded-[24px] bg-white/[0.06] border border-white/10 p-[1px]"><div className="rounded-[23px] bg-[#121212] p-5">
<div className="grid grid-cols-3 gap-2">
<select value={d} onChange={e=>setD(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">วัน</option>{Array.from({length:max},(_,i)=>i+1).map(v=><option key={v} value={v}>{v}</option>)}</select>
<select value={mo} onChange={e=>setMo(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">เดือน</option>{Array.from({length:12},(_,i)=>i+1).map(v=><option key={v} value={v}>{v}</option>)}</select>
<select value={y} onChange={e=>setY(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">ปี พ.ศ.</option>{Array.from({length:100},(_,i)=>2569-i).map(be=><option key={be} value={be-543}>{be}</option>)}</select>
</div>
<div className="mt-3 grid grid-cols-2 gap-2">
<select value={h} disabled={ut} onChange={e=>setH(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white disabled:opacity-20"><option value="">ชั่วโมง</option>{Array.from({length:24},(_,i)=>i).map(v=><option key={v} value={v}>{String(v).padStart(2,"0")} น.</option>)}</select>
<select value={mi} disabled={ut} onChange={e=>setMi(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white disabled:opacity-20"><option value="">นาที</option>{Array.from({length:60},(_,i)=>i).map(v=><option key={v} value={v}>{String(v).padStart(2,"0")} นาที</option>)}</select>
</div>
<label className="flex items-center gap-2 text-xs text-yellow-300 mt-3"><input type="checkbox" checked={ut} onChange={e=>setUt(e.target.checked)} /> ไม่ทราบเวลาเกิด</label>
<button onClick={calc} className="mt-4 w-full rounded-xl bg-gradient-to-b from-[#f5e6c8] to-[#d4af37] text-black font-bold py-4">ทำนายดวงชะตาแบบละเอียด</button>
</div></div>
{r && (
<div ref={rr} className="mt-8 space-y-6">
<div className="rounded-[24px] bg-[#121212] border border-yellow-500/20 p-5"><h2 className="text-center text-[#f5e6c8]">แผนผังสี่เสาหลัก</h2><div className="mt-4 grid grid-cols-4 gap-2">{[{p:r.year,l:"ปี"},{p:r.month,l:"เดือน"},{p:r.day,l:"วัน"},{p:r.dh,l:"ยาม"}].map((it:any,i:number)=>{if(!it.p)return <div key={i} className="rounded-xl bg-yellow-500/10 p-4 text-center text-xs">ไม่ทราบเวลา</div>;const z=zd[it.p.branchZh];return <div key={i}><div className="text-[9px] text-center text-white/30">{it.l}</div><div className="rounded-xl overflow-hidden border border-yellow-500/20 aspect-[3/4] bg-black"><img src={`/bazi/${z.a}-${it.p.element}.webp`} className="w-full h-full object-cover" /></div><div className="text-center text-[10px] text-[#f5e6c8] mt-1">{it.p.stemZh}{it.p.branchZh}</div></div>;})}</div></div>
<div className="rounded-[24px] bg-[#121212] border border-white/[0.06] p-6"><h3 className="text-center text-[#f5e6c8] font-bold">สมดุลเบญจธาตุ</h3><p className="text-center text-[11px] text-white/40 mt-1">แต่ละคนไม่เหมือนกัน คำนวณจากดวงคุณจริงๆ</p><div className="mt-6 flex flex-col sm:flex-row items-center justify-center gap-8"><div><svg width="180" height="180" viewBox="0 0 200 200">{(()=>{const data=[{p:r.elementPercent?.wood||0,c:"#22c55e"},{p:r.elementPercent?.fire||0,c:"#ef4444"},{p:r.elementPercent?.earth||0,c:"#eab308"},{p:r.elementPercent?.metal||0,c:"#e5e7eb"},{p:r.elementPercent?.water||0,c:"#60a5fa"}];let acc=0;return data.map((d,i)=>{const s=acc;acc+=d.p;const e=acc;if(d.p<=0)return null;const sa=(s/100)*360-90,ea=(e/100)*360-90;const ro=80,ri=50;const x1=100+ro*Math.cos(sa*Math.PI/180),y1=100+ro*Math.sin(sa*Math.PI/180);const x2=100+ro*Math.cos(ea*Math.PI/180),y2=100+ro*Math.sin(ea*Math.PI/180);const x3=100+ri*Math.cos(ea*Math.PI/180),y3=100+ri*Math.sin(ea*Math.PI/180);const x4=100+ri*Math.cos(sa*Math.PI/180),y4=100+ri*Math.sin(sa*Math.PI/180);const large=d.p>50?1:0;return <path key={i} d={`M ${x1} ${y1} A ${ro} ${ro} 0 ${large} 1 ${x2} ${y2} L ${x3} ${y3} A ${ri} ${ri} 0 ${large} 0 ${x4} ${y4} Z`} fill={d.c} stroke="#121212" strokeWidth="2"/>});})()}<circle cx="100" cy="100" r="42" fill="#121212" stroke="rgba(212,175,55,0.3)" /><text x="100" y="100" textAnchor="middle" dy="0.3em" fill="#f5e6c8" fontSize="11">ธาตุ</text></svg></div><div className="space-y-3 w-full sm:w-[260px]">{[{k:"wood",th:"ไม้",c:"#22c55e",p:r.elementPercent?.wood||0},{k:"fire",th:"ไฟ",c:"#ef4444",p:r.elementPercent?.fire||0},{k:"earth",th:"ดิน",c:"#eab308",p:r.elementPercent?.earth||0},{k:"metal",th:"ทอง",c:"#e5e7eb",p:r.elementPercent?.metal||0},{k:"water",th:"น้ำ",c:"#60a5fa",p:r.elementPercent?.water||0}].map((el:any)=>{const s=st(el.p);return (<div key={el.k}><div className="flex justify-between text-[11px]"><span className="text-white/60">{el.th} {s}</span><span className="text-white/80 font-bold">{el.p.toFixed(1)}%</span></div><div className="mt-1 h-[6px] bg-white/10 rounded-full overflow-hidden"><div className="h-full rounded-full" style={{width:`${el.p}%`,background:el.c}} /></div></div>);})}</div></div></div>
<div className="rounded-[24px] bg-[#f5f1e8] text-[#2c2416] p-6 border-[6px] border-[#d4af37]"><h2 className="text-xl text-[#8b5a00] text-center font-bold">วิเคราะห์ดวงชะตาของคุณ</h2><p className="text-center text-[11px] text-[#8b5a00]/60 mt-1">{r.dy}/{r.mo}/{r.yr+543} {r.hr!==null?`${String(r.hr).padStart(2,"0")}:${String(r.mn).padStart(2,"0")} น.`:"ไม่ทราบเวลา"}</p><div className="mt-4 space-y-4 text-[14px] leading-[1.8]"><div className="bg-white p-4 rounded-xl border"><b>ดวงของคุณคือ</b> {r.year?.stemZh}{r.year?.branchZh} {r.month?.stemZh}{r.month?.branchZh} {r.day?.stemZh}{r.day?.branchZh} {r.dh?.stemZh}{r.dh?.branchZh} - ปี {r.year?.branchTh} เดือน {r.month?.branchTh} วัน {r.day?.branchTh} ยาม {r.dh?.branchTh}</div><div className="bg-[#fffaf0] p-4 rounded-xl border"><b>1. Life Path {r.lp} - {lpData[r.lp]?.t}</b><br/>{r.dy}+{r.mo}+{r.yr}={r.dy+r.mo+r.yr}={r.lp} คุณเป็นเลข {r.lp} {lpData[r.lp]?.d}<br/><br/><b className="text-[#8b5a00]">{lpData[r.lp]?.r}</b></div><div className="bg-[#fffaf0] p-4 rounded-xl border"><b>2. พลังธาตุในดวงคุณ</b><br/>ธาตุประจำตัวคุณคือธาตุ{r.day?.stemTh} ({r.day?.element})<br/><br/>{[
{th:"ไม้",p:r.elementPercent?.wood||0,en:"ความคิดริเริ่ม การเติบโต"},
{th:"ไฟ",p:r.elementPercent?.fire||0,en:"ความโดดเด่น เสน่ห์ การแสดงออก"},
{th:"ดิน",p:r.elementPercent?.earth||0,en:"ความมั่นคง คลังเงิน"},
{th:"ทอง",p:r.elementPercent?.metal||0,en:"ระเบียบ วินัย การจัดการ"},
{th:"น้ำ",p:r.elementPercent?.water||0,en:"ปัญญา การไหลเวียน"}
].map((e:any)=>{const s=st(e.p); let d=""; if(e.th==="น้ำ"){if(e.p>=35) d="น้ำเยอะมาก มีปัญญามาก ปรับตัวเก่ง แต่คิดมาก เงินไหลออกเร็ว ต้องมีดินมากั้น"; else if(e.p>=25) d="น้ำมีพลังมาก ฉลาด ปรับตัวเก่ง ไหลเวียนดี"; else if(e.p>=15) d="น้ำสมดุลดี มีปัญญาพอดี"; else if(e.p>=8) d="น้ำค่อนข้างน้อย ต้องเสริมการเรียนรู้ สื่อสาร เดินทาง"; else d="น้ำอ่อน ปัญญาและการไหลของเงินอ่อน ต้องเติมด้วยการเรียนรู้ สื่อสาร";} if(e.th==="ไม้"){if(e.p>=35) d="ไม้เยอะมาก ความคิดใหม่เยอะ โตเร็ว แต่ทำหลายอย่างพร้อมกัน ต้องมีทองมาตัด"; else if(e.p>=25) d="ไม้มีพลังมาก ไอเดียเยอะ โตเร็ว"; else if(e.p>=15) d="ไม้สมดุลดี"; else if(e.p>=8) d="ไม้ค่อนข้างน้อย"; else d="ไม้อ่อน ขาดความคิดริเริ่ม";} if(e.th==="ไฟ"){if(e.p>=35) d="ไฟเยอะมาก โดดเด่นมาก ร้อน ต้องมีน้ำมาดับ"; else if(e.p>=25) d="ไฟมีพลังมาก นำเสนอเก่ง มีเสน่ห์"; else if(e.p>=15) d="ไฟสมดุลดี"; else if(e.p>=8) d="ไฟค่อนข้างน้อย"; else d="ไฟอ่อน ไม่ค่อยกล้าแสดงออก";} if(e.th==="ดิน"){if(e.p>=35) d="ดินเยอะมาก มั่นคงมาก เก็บเงินเก่ง แต่ยึดติด"; else if(e.p>=25) d="ดินมีพลังมาก มั่นคง เก็บเงินเก่ง"; else if(e.p>=15) d="ดินสมดุลดี"; else if(e.p>=8) d="ดินค่อนข้างน้อย คลังเงินเล็ก"; else d="ดินอ่อน ไม่มีคลังเงิน เก็บยาก";} if(e.th==="ทอง"){if(e.p>=35) d="ทองเยอะมาก ระเบียบจัด เข้มงวด ต้องมีไฟมาหลอม"; else if(e.p>=25) d="ทองมีพลังมาก มีระเบียบ วินัย"; else if(e.p>=15) d="ทองสมดุลดี"; else if(e.p>=8) d="ทองค่อนข้างน้อย"; else d="ทองอ่อน ขาดระเบียบ";} return `- ${e.th} ${s} ${e.p.toFixed(1)}% - ${d}`;}).join('<br/><br/>')}</div><div className="bg-white p-4 rounded-xl border"><b>3. การงาน การเงิน และวิธีปรับสมดุลเฉพาะคุณ</b><br/><br/><b>การงาน:</b> {(()=>{
const wood=r.elementPercent?.wood||0,metal=r.elementPercent?.metal||0,water=r.elementPercent?.water||0,fire=r.elementPercent?.fire||0;
if(wood>=30&&metal<12) return `คุณไม้ ${st(wood)} ${wood.toFixed(1)}% เยอะมาก แต่ทอง ${st(metal)} ${metal.toFixed(1)}% น้อย คุณมีความคิดริเริ่มสูงมากแต่ขาดตัวตัดให้เป็นชิ้นงาน คุณจะรุ่งเมื่องานมีกรอบชัด มี KPI มีระบบ ไม่ใช่งานอิสระลอยๆ`;
if(water>=30) return `คุณน้ำ ${st(water)} ${water.toFixed(1)}% เยอะมาก คุณฉลาด ปรับตัวเก่ง เหมาะกับงานสื่อสาร เดินทาง วิเคราะห์ข้อมูล งานที่ต้องใช้ปัญญา`;
if(fire>=30) return `คุณไฟ ${st(fire)} ${fire.toFixed(1)}% เยอะมาก คุณโดดเด่น มีเสน่ห์ เหมาะกับงานออกหน้า ขาย นำเสนอ`;
return `ดวงคุณธาตุ${r.day?.element}เด่น คุณเหมาะกับงานที่ใช้ธาตุ${r.day?.element}เป็นหลัก และควรเสริมธาตุที่อ่อน`;
})()}<br/><br/><b>การเงิน:</b> {zd[r.month?.branchZh]?.th} ({r.month?.branchZh}) เป็นคลังเงิน {(()=>{
const e=r.elementPercent?.earth||0; if(e>=20) return `ดิน ${st(e)} ${e.toFixed(1)}% แข็งแรง คุณเก็บเงินเก่ง มั่นคง`; if(e>=10) return `ดิน ${st(e)} ${e.toFixed(1)}% พอดี คุณหาเงินเก่งแต่ต้องระวังใช้จ่าย`; return `ดิน ${st(e)} ${e.toFixed(1)}% อ่อน คลังเงินเล็ก คุณหาเงินเก่งแต่เก็บยากมาก ต้องสร้างระบบออมอัตโนมัติ`;})()}<br/><br/><b>วิธีปรับสมดุลเฉพาะดวงคุณ:</b><br/>{(()=>{
const w=r.elementPercent?.wood||0,f=r.elementPercent?.fire||0,e=r.elementPercent?.earth||0,m=r.elementPercent?.metal||0,wa=r.elementPercent?.water||0;
let t=[]; if(w<8) t.push(`• ไม้ ${st(w)} ${w.toFixed(1)}% อ่อน - เติมไม้ สีเขียว ทิศตะวันออก`); if(f<8) t.push(`• ไฟ ${st(f)} ${f.toFixed(1)}% อ่อน - เติมไฟ สีแดง ส้ม ทิศใต้`); if(e<8) t.push(`• ดิน ${st(e)} ${e.toFixed(1)}% อ่อน - เติมดิน สีเหลือง น้ำตาล ทิศกลาง`); if(m<8) t.push(`• ทอง ${st(m)} ${m.toFixed(1)}% อ่อน - เติมทอง สีขาว เทา ทิศตะวันตก`); if(wa<8) t.push(`• น้ำ ${st(wa)} ${wa.toFixed(1)}% อ่อน - เติมน้ำ สีดำ น้ำเงิน ทิศเหนือ`); if(w>=35) t.push(`• ไม้ ${st(w)} ${w.toFixed(1)}% เยอะเกิน - ต้องมีทองมาตัด เพิ่มระเบียบ KPI`); if(wa>=35) t.push(`• น้ำ ${st(wa)} ${wa.toFixed(1)}% เยอะเกิน - น้ำล้น ต้องมีดินมากั้น มีไฟมาอุ่น อย่าให้คิดมากเกิน`); if(f>=35) t.push(`• ไฟ ${st(f)} ${f.toFixed(1)}% เยอะเกิน - ต้องมีน้ำมาดับ ใจเย็นลง`); if(t.length===0) t.push(`• ดวงคุณค่อนข้างสมดุลดีแล้วครับ รักษาสมดุลนี้ไว้`); return t.join("<br/>");})()}<br/><br/>อายุ {new Date().getFullYear()-r.yr} ย่าง {new Date().getFullYear()-r.yr+1} ปี เป็นวัยที่ควรเริ่มวางระบบให้ชีวิตมั่นคงขึ้น จากลงมือทำเองทุกอย่าง ค่อยๆ เปลี่ยนมาเป็นวางระบบแล้วให้คนอื่นช่วยทำ จะเหนื่อยน้อยลงแต่ผลลัพธ์มั่นคงขึ้นครับ</div></div></div>
<div className="rounded-[24px] bg-gradient-to-br from-[#1a1508] to-[#0f0e0a] border border-yellow-500/30 p-[1px]"><div className="rounded-[23px] bg-[#121212] p-6 text-center"><h3 className="text-[#f5e6c8] font-bold text-lg">อยากรู้ลึกกว่านี้ใช่ไหมครับ?</h3><p className="text-[13px] text-white/60 mt-2">นี่เป็นแค่ภาพรวม 4 เสาหลักเท่านั้นนะครับ<br/>ยังมี <b className="text-[#d4af37]">12 เข็มทิศชีวิต</b> ที่วิเคราะห์ลึกถึงอาชีพที่ใช่ คู่ที่เสริม ทิศทางเงิน 10 ปีข้างหน้า</p><div className="mt-5 rounded-xl bg-gradient-to-b from-[#f5e6c8] to-[#d4af37] p-[1px]"><a href="https://lin.ee/Qtt1m4cC" target="_blank" className="block rounded-[11px] bg-gradient-to-b from-[#f5e6c8] to-[#d4af37] text-black font-bold py-4 text-center">📲 แอดไลน์ ดู 12 เข็มทิศชีวิตแบบละเอียด</a></div><p className="text-[10px] text-white/40 mt-3">เราตั้งใจทำเพื่ออยากช่วยคุณจริงๆ ครับ</p></div></div>
</div>
)}
</div></main>
);
}
