"use client";
import { useState, useRef, useMemo } from "react";
import { calculateBazi } from "@/lib/bazi";
const dm=(y:number,m:number)=>new Date(y,m,0).getDate();
const zd:any={"子":{th:"ชวด",a:"rat"},"丑":{th:"ฉลู",a:"ox"},"寅":{th:"ขาล",a:"tiger"},"卯":{th:"เถาะ",a:"rabbit"},"辰":{th:"มะโรง",a:"dragon"},"巳":{th:"มะเส็ง",a:"snake"},"午":{th:"มะเมีย",a:"horse"},"未":{th:"มะแม",a:"goat"},"申":{th:"วอก",a:"monkey"},"酉":{th:"ระกา",a:"rooster"},"戌":{th:"จอ",a:"dog"},"亥":{th:"กุน",a:"pig"}};
export default function Home(){
const [y,setY]=useState<any>('');const [mo,setMo]=useState<any>('');const [d,setD]=useState<any>('');const [h,setH]=useState<any>('');const [mi,setMi]=useState<any>('');const [ut,setUt]=useState(false);
const [r,setR]=useState<any>(null);const rr=useRef<HTMLDivElement>(null);
const max=useMemo(()=>{if(!y||!mo)return 31;return dm(Number(y),Number(mo));},[y,mo]);
function lp(a:number,b:number,c:number){let t=a+b+c;while(t>9){t=String(t).split('').reduce((x:any,y:any)=>x+Number(y),0);}return t;}
function calc(){
if(y===''||mo===''||d===''){alert("เลือก วัน เดือน ปี");return;}
if(!ut&&(h===''||mi==='')){alert("เลือก ชั่วโมง นาที หรือติ๊กไม่ทราบเวลา");return;}
try{const raw=calculateBazi({year:Number(y),month:Number(mo),day:Number(d),hour:ut?12:Number(h),minute:ut?0:Number(mi)});const l=lp(Number(d),Number(mo),Number(y));setR({...raw,ut,dh:ut?null:raw.hour,lp:l,dy:Number(d),mo:Number(mo),yr:Number(y),hr:ut?null:Number(h),mn:ut?null:Number(mi)});setTimeout(()=>rr.current?.scrollIntoView({behavior:"smooth"}),300);}catch(e:any){alert(e.message);}}
return(<main className="min-h-screen bg-[#060606] text-white"><div className="max-w-[900px] mx-auto px-4 py-8">
<div className="text-center mb-6"><h1 className="text-[36px] font-bold text-[#f5e6c8]">ทำดวงจีนปาจื้อ</h1></div>
<div className="rounded-[24px] bg-white/[0.06] border border-white/10 p-[1px]"><div className="rounded-[23px] bg-[#121212] p-5">
<div className="grid grid-cols-3 gap-2">
<select value={d} onChange={e=>setD(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">วัน</option>{Array.from({length:max},(_,i)=>i+1).map(v=><option key={v} value={v}>{v}</option>)}</select>
<select value={mo} onChange={e=>setMo(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">เดือน</option>{Array.from({length:12},(_,i)=>i+1).map(v=><option key={v} value={v}>{v}</option>)}</select>
<select value={y} onChange={e=>setY(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white"><option value="">ปี พ.ศ.</option>{Array.from({length:80},(_,i)=>2560-i).map(be=><option key={be} value={be-543}>{be}</option>)}</select>
</div>
<div className="mt-3 grid grid-cols-2 gap-2">
<select value={h} disabled={ut} onChange={e=>setH(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white disabled:opacity-20"><option value="">ชั่วโมง</option>{Array.from({length:24},(_,i)=>i).map(v=><option key={v} value={v}>{String(v).padStart(2,"0")} น.</option>)}</select>
<select value={mi} disabled={ut} onChange={e=>setMi(e.target.value===''? '': Number(e.target.value))} className="rounded-xl bg-[#1e1e1e] border border-white/10 px-3 py-3 text-sm text-white disabled:opacity-20"><option value="">นาที</option>{Array.from({length:60},(_,i)=>i).map(v=><option key={v} value={v}>{String(v).padStart(2,"0")} นาที</option>)}</select>
</div>
<label className="flex items-center gap-2 text-xs text-yellow-300 mt-3"><input type="checkbox" checked={ut} onChange={e=>setUt(e.target.checked)} /> ไม่ทราบเวลาเกิด</label>
<button onClick={calc} className="mt-4 w-full rounded-xl bg-gradient-to-b from-[#f5e6c8] to-[#d4af37] text-black font-bold py-4">ทำนายดวงชะตาแบบละเอียด</button>
</div></div>
{r && (
<div ref={rr} className="mt-8 space-y-6">
<div className="rounded-[24px] bg-[#121212] border border-yellow-500/20 p-5"><h2 className="text-center text-[#f5e6c8]">แผนผังสี่เสาหลัก</h2><div className="mt-4 grid grid-cols-4 gap-2">{[{p:r.year,l:"ปี"},{p:r.month,l:"เดือน"},{p:r.day,l:"วัน"},{p:r.dh,l:"ยาม"}].map((it:any,i:number)=>{if(!it.p)return <div key={i} className="rounded-xl bg-yellow-500/10 p-4 text-center text-xs">ไม่ทราบเวลา</div>;const z=zd[it.p.branchZh];return <div key={i}><div className="text-[9px] text-center text-white/30">{it.l}</div><div className="rounded-xl overflow-hidden border border-yellow-500/20 aspect-[3/4] bg-black"><img src={`/bazi/${z.a}-${it.p.element}.webp`} className="w-full h-full object-cover" /></div><div className="text-center text-[10px] text-[#f5e6c8] mt-1">{it.p.stemZh}{it.p.branchZh}</div></div>;})}</div></div>
<div className="rounded-[24px] bg-[#121212] border border-white/[0.06] p-6"><h3 className="text-center text-[#f5e6c8] font-bold">สมดุลเบญจธาตุ · พลัง 5 ธาตุ</h3><div className="mt-6 flex flex-col sm:flex-row items-center justify-center gap-8"><div><svg width="180" height="180" viewBox="0 0 200 200">{(()=>{const data=[{p:r.elementPercent?.wood||0,c:"#22c55e"},{p:r.elementPercent?.fire||0,c:"#ef4444"},{p:r.elementPercent?.earth||0,c:"#eab308"},{p:r.elementPercent?.metal||0,c:"#e5e7eb"},{p:r.elementPercent?.water||0,c:"#60a5fa"}];let acc=0;return data.map((d,i)=>{const s=acc;acc+=d.p;const e=acc;if(d.p<=0)return null;const sa=(s/100)*360-90,ea=(e/100)*360-90;const ro=80,ri=50;const x1=100+ro*Math.cos(sa*Math.PI/180),y1=100+ro*Math.sin(sa*Math.PI/180);const x2=100+ro*Math.cos(ea*Math.PI/180),y2=100+ro*Math.sin(ea*Math.PI/180);const x3=100+ri*Math.cos(ea*Math.PI/180),y3=100+ri*Math.sin(ea*Math.PI/180);const x4=100+ri*Math.cos(sa*Math.PI/180),y4=100+ri*Math.sin(sa*Math.PI/180);const large=d.p>50?1:0;return <path key={i} d={`M ${x1} ${y1} A ${ro} ${ro} 0 ${large} 1 ${x2} ${y2} L ${x3} ${y3} A ${ri} ${ri} 0 ${large} 0 ${x4} ${y4} Z`} fill={d.c} stroke="#121212" strokeWidth="2"/>});})()}<circle cx="100" cy="100" r="42" fill="#121212" stroke="rgba(212,175,55,0.3)" /><text x="100" y="100" textAnchor="middle" dy="0.3em" fill="#f5e6c8" fontSize="11">ธาตุ</text></svg></div><div className="space-y-3 w-full sm:w-[260px]">{[{k:"wood",th:"ไม้",c:"#22c55e",p:r.elementPercent?.wood||0},{k:"fire",th:"ไฟ",c:"#ef4444",p:r.elementPercent?.fire||0},{k:"earth",th:"ดิน",c:"#eab308",p:r.elementPercent?.earth||0},{k:"metal",th:"ทอง",c:"#e5e7eb",p:r.elementPercent?.metal||0},{k:"water",th:"น้ำ",c:"#60a5fa",p:r.elementPercent?.water||0}].map((el:any)=>(<div key={el.k}><div className="flex justify-between text-[11px]"><span className="text-white/50">{el.th}</span><span className="text-white/70">{el.p.toFixed(1)}%</span></div><div className="mt-1 h-[6px] bg-white/10 rounded-full overflow-hidden"><div className="h-full rounded-full" style={{width:`${el.p}%`,background:el.c}} /></div></div>))}</div></div></div>
<div className="rounded-[24px] bg-[#f5f1e8] text-[#2c2416] p-6 border-[6px] border-[#d4af37]"><h2 className="text-xl text-[#8b5a00] text-center font-bold">วิเคราะห์ดวงชะตาของคุณ</h2><p className="text-center text-[11px] text-[#8b5a00]/60 mt-1">{r.dy}/{r.mo}/{r.yr+543} {r.hr!==null?`${String(r.hr).padStart(2,"0")}:${String(r.mn).padStart(2,"0")} น. ยาม ${r.dh?.branchTh}`:"ไม่ทราบเวลา"}</p><div className="mt-4 space-y-3 text-[13px] leading-[1.7]"><div className="bg-white p-3 rounded-xl border"><b>ข้อมูลดวง:</b> {r.year?.stemZh}{r.year?.branchZh}年 {r.month?.stemZh}{r.month?.branchZh}月 {r.day?.stemZh}{r.day?.branchZh}日 {r.dh?.stemZh}{r.dh?.branchZh}時 - ปี {r.year?.branchTh} เดือน {r.month?.branchTh} วัน {r.day?.branchTh} ยาม {r.dh?.branchTh}</div><div className="bg-[#fffaf0] p-3 rounded-xl border"><b>1. Life Path {r.lp}:</b> {r.dy}+{r.mo}+{r.yr}={r.dy+r.mo+r.yr}={r.lp} - เลข {r.lp} นักวิเคราะห์ ชอบขุดลึก</div><div className="bg-[#fffaf0] p-3 rounded-xl border"><b>2. สายธาตุ - ธาตุ{r.day?.stemTh} {r.day?.element}</b> - ไม้ {(r.elementPercent?.wood||0).toFixed(1)}% ไฟ {(r.elementPercent?.fire||0).toFixed(1)}% ดิน {(r.elementPercent?.earth||0).toFixed(1)}% ทอง {(r.elementPercent?.metal||0).toFixed(1)}% น้ำ {(r.elementPercent?.water||0).toFixed(1)}%</div><div className="bg-white p-3 rounded-xl border"><b>การงาน:</b> ไม้เยอะต้องมีทองมาตัด รุ่งเมื่อมีกรอบชัด KPI ระบบ<br/><b>การเงิน:</b> {r.month?.branchTh} คลังเงิน หาเงินเก่งเก็บยาก ต้องทำบัญชี แยกกระเป๋า<br/><b>วิธีปรับธาตุ:</b> เติมน้ำทอง สีขาว เทา ดำ น้ำเงิน ทิศเหนือ ตะวันตก</div></div></div>
<div className="rounded-[24px] bg-gradient-to-br from-[#1a1508] to-[#0f0e0a] border border-yellow-500/30 p-[1px]"><div className="rounded-[23px] bg-[#121212] p-6 text-center"><h3 className="text-[#f5e6c8] font-bold text-lg">อยากรู้ลึกกว่านี้ใช่ไหม?</h3><p className="text-[13px] text-white/60 mt-2">ยังมี <b className="text-[#d4af37]">12 เข็มทิศชีวิต (12 Compass)</b> วิเคราะห์ลึกถึง อาชีพที่ใช่ คู่ที่เสริม ทิศทางเงิน โชคลาภ 10 ปีข้างหน้า</p><div className="mt-5 rounded-xl bg-gradient-to-b from-[#f5e6c8] to-[#d4af37] p-[1px]"><a href="https://lin.ee/Qtt1m4cC" target="_blank" className="block rounded-[11px] bg-gradient-to-b from-[#f5e6c8] to-[#d4af37] text-black font-bold py-4 text-center">📲 แอดไลน์ ดู 12 เข็มทิศชีวิตแบบละเอียด คลิกเลย</a></div><p className="text-[10px] text-white/30 mt-3">แก้ https://lin.ee/Qtt1m4cC เป็นลิงก์ไลน์ของคุณ เช่น https://line.me/ti/p/@yourid</p></div></div>
</div>
)}
</div></main>
);
}
